// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum Permission: Int {
  case camera = 0
}

enum PermissionStatus: Int {
  case granted = 0
  case denied = 1
  case error = 2
}

enum RegistrationState: Int {
  case registered = 0
  case registering = 1
  case unregistered = 2
  case unregistering = 3
  case unavailable = 4
  case error = 5
}

enum VideoQuality: Int {
  case low = 0
  case medium = 1
  case high = 2
}

enum StreamState: Int {
  case stopped = 0
  case waitingForDevice = 1
  case starting = 2
  case streaming = 3
  case stopping = 4
  case paused = 5
}

/// Generated class from Pigeon that represents data sent in messages.
struct PermissionResult: Hashable {
  var status: PermissionStatus
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionResult? {
    let status = pigeonVar_list[0] as! PermissionStatus
    let message: String? = nilOrValue(pigeonVar_list[1])

    return PermissionResult(
      status: status,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      message,
    ]
  }
  static func == (lhs: PermissionResult, rhs: PermissionResult) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RegistrationUpdate: Hashable {
  var state: RegistrationState
  var description: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegistrationUpdate? {
    let state = pigeonVar_list[0] as! RegistrationState
    let description: String? = nilOrValue(pigeonVar_list[1])

    return RegistrationUpdate(
      state: state,
      description: description
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      description,
    ]
  }
  static func == (lhs: RegistrationUpdate, rhs: RegistrationUpdate) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StreamConfig: Hashable {
  var quality: VideoQuality
  var frameRate: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StreamConfig? {
    let quality = pigeonVar_list[0] as! VideoQuality
    let frameRate = pigeonVar_list[1] as! Int64

    return StreamConfig(
      quality: quality,
      frameRate: frameRate
    )
  }
  func toList() -> [Any?] {
    return [
      quality,
      frameRate,
    ]
  }
  static func == (lhs: StreamConfig, rhs: StreamConfig) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoFrameData: Hashable {
  var data: FlutterStandardTypedData
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoFrameData? {
    let data = pigeonVar_list[0] as! FlutterStandardTypedData
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64

    return VideoFrameData(
      data: data,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      data,
      width,
      height,
    ]
  }
  static func == (lhs: VideoFrameData, rhs: VideoFrameData) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PhotoData: Hashable {
  var data: FlutterStandardTypedData
  var format: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PhotoData? {
    let data = pigeonVar_list[0] as! FlutterStandardTypedData
    let format = pigeonVar_list[1] as! String

    return PhotoData(
      data: data,
      format: format
    )
  }
  func toList() -> [Any?] {
    return [
      data,
      format,
    ]
  }
  static func == (lhs: PhotoData, rhs: PhotoData) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ErrorInfo: Hashable {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ErrorInfo? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return ErrorInfo(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: ErrorInfo, rhs: ErrorInfo) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return Permission(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RegistrationState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VideoQuality(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return StreamState(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return PermissionResult.fromList(self.readValue() as! [Any?])
    case 135:
      return RegistrationUpdate.fromList(self.readValue() as! [Any?])
    case 136:
      return StreamConfig.fromList(self.readValue() as! [Any?])
    case 137:
      return VideoFrameData.fromList(self.readValue() as! [Any?])
    case 138:
      return PhotoData.fromList(self.readValue() as! [Any?])
    case 139:
      return ErrorInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Permission {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? RegistrationState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoQuality {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? StreamState {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RegistrationUpdate {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? StreamConfig {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? VideoFrameData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PhotoData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ErrorInfo {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WearablesHostApi {
  func initialize() throws
  func checkPermission(permission: Permission, completion: @escaping (Result<PermissionResult, Error>) -> Void)
  func requestPermission(permission: Permission, completion: @escaping (Result<PermissionResult, Error>) -> Void)
  func getRegistrationState(completion: @escaping (Result<RegistrationUpdate, Error>) -> Void)
  func startRegistration(completion: @escaping (Result<Void, Error>) -> Void)
  func startUnregistration(completion: @escaping (Result<Void, Error>) -> Void)
  func startStream(config: StreamConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func stopStream() throws
  func capturePhoto() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WearablesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `WearablesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WearablesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        do {
          try api.initialize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let checkPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.checkPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionArg = args[0] as! Permission
        api.checkPermission(permission: permissionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkPermissionChannel.setMessageHandler(nil)
    }
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionArg = args[0] as! Permission
        api.requestPermission(permission: permissionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let getRegistrationStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.getRegistrationState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRegistrationStateChannel.setMessageHandler { _, reply in
        api.getRegistrationState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRegistrationStateChannel.setMessageHandler(nil)
    }
    let startRegistrationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.startRegistration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRegistrationChannel.setMessageHandler { _, reply in
        api.startRegistration { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startRegistrationChannel.setMessageHandler(nil)
    }
    let startUnregistrationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.startUnregistration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startUnregistrationChannel.setMessageHandler { _, reply in
        api.startUnregistration { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startUnregistrationChannel.setMessageHandler(nil)
    }
    let startStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.startStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! StreamConfig
        api.startStream(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startStreamChannel.setMessageHandler(nil)
    }
    let stopStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.stopStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopStreamChannel.setMessageHandler { _, reply in
        do {
          try api.stopStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopStreamChannel.setMessageHandler(nil)
    }
    let capturePhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.meta_wearables.WearablesHostApi.capturePhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      capturePhotoChannel.setMessageHandler { _, reply in
        do {
          try api.capturePhoto()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      capturePhotoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WearablesFlutterApiProtocol {
  func onRegistrationStateChanged(update updateArg: RegistrationUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStreamStateChanged(state stateArg: StreamState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onVideoFrame(frame frameArg: VideoFrameData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPhotoCaptured(photo photoArg: PhotoData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(error errorArg: ErrorInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WearablesFlutterApi: WearablesFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonPigeonCodec {
    return PigeonPigeonCodec.shared
  }
  func onRegistrationStateChanged(update updateArg: RegistrationUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onRegistrationStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStreamStateChanged(state stateArg: StreamState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onStreamStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onVideoFrame(frame frameArg: VideoFrameData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onVideoFrame\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([frameArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPhotoCaptured(photo photoArg: PhotoData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onPhotoCaptured\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([photoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onError(error errorArg: ErrorInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
