// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.chunkytofustudios.meta_wearables.meta_wearables

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class Permission(val raw: Int) {
  CAMERA(0);

  companion object {
    fun ofRaw(raw: Int): Permission? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PermissionStatus(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): PermissionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RegistrationState(val raw: Int) {
  REGISTERED(0),
  REGISTERING(1),
  UNREGISTERED(2),
  UNREGISTERING(3),
  UNAVAILABLE(4),
  ERROR(5);

  companion object {
    fun ofRaw(raw: Int): RegistrationState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VideoQuality(val raw: Int) {
  LOW(0),
  MEDIUM(1),
  HIGH(2);

  companion object {
    fun ofRaw(raw: Int): VideoQuality? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class StreamState(val raw: Int) {
  STOPPED(0),
  WAITING_FOR_DEVICE(1),
  STARTING(2),
  STREAMING(3),
  STOPPING(4),
  PAUSED(5);

  companion object {
    fun ofRaw(raw: Int): StreamState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PermissionResult (
  val status: PermissionStatus,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionResult {
      val status = pigeonVar_list[0] as PermissionStatus
      val message = pigeonVar_list[1] as String?
      return PermissionResult(status, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PermissionResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RegistrationUpdate (
  val state: RegistrationState,
  val description: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegistrationUpdate {
      val state = pigeonVar_list[0] as RegistrationState
      val description = pigeonVar_list[1] as String?
      return RegistrationUpdate(state, description)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      description,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RegistrationUpdate) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StreamConfig (
  val quality: VideoQuality,
  val frameRate: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamConfig {
      val quality = pigeonVar_list[0] as VideoQuality
      val frameRate = pigeonVar_list[1] as Long
      return StreamConfig(quality, frameRate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      quality,
      frameRate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StreamConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoFrameData (
  val data: ByteArray,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoFrameData {
      val data = pigeonVar_list[0] as ByteArray
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return VideoFrameData(data, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VideoFrameData) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhotoData (
  val data: ByteArray,
  val format: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhotoData {
      val data = pigeonVar_list[0] as ByteArray
      val format = pigeonVar_list[1] as String
      return PhotoData(data, format)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      format,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PhotoData) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ErrorInfo (
  val code: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ErrorInfo {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return ErrorInfo(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ErrorInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Permission.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RegistrationState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VideoQuality.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          StreamState.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegistrationUpdate.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamConfig.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoFrameData.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhotoData.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Permission -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is RegistrationState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is VideoQuality -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is StreamState -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RegistrationUpdate -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is StreamConfig -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is VideoFrameData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PhotoData -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ErrorInfo -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WearablesHostApi {
  fun initialize()
  fun checkPermission(permission: Permission, callback: (Result<PermissionResult>) -> Unit)
  fun requestPermission(permission: Permission, callback: (Result<PermissionResult>) -> Unit)
  fun getRegistrationState(callback: (Result<RegistrationUpdate>) -> Unit)
  fun startRegistration(callback: (Result<Unit>) -> Unit)
  fun startUnregistration(callback: (Result<Unit>) -> Unit)
  fun startStream(config: StreamConfig, callback: (Result<Unit>) -> Unit)
  fun stopStream()
  fun capturePhoto()

  companion object {
    /** The codec used by WearablesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `WearablesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WearablesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initialize()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.checkPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionArg = args[0] as Permission
            api.checkPermission(permissionArg) { result: Result<PermissionResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionArg = args[0] as Permission
            api.requestPermission(permissionArg) { result: Result<PermissionResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.getRegistrationState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRegistrationState{ result: Result<RegistrationUpdate> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.startRegistration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startRegistration{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.startUnregistration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startUnregistration{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.startStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as StreamConfig
            api.startStream(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.stopStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopStream()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.meta_wearables.WearablesHostApi.capturePhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.capturePhoto()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class WearablesFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WearablesFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
  }
  fun onRegistrationStateChanged(updateArg: RegistrationUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onRegistrationStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStreamStateChanged(stateArg: StreamState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onStreamStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onVideoFrame(frameArg: VideoFrameData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onVideoFrame$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(frameArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPhotoCaptured(photoArg: PhotoData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onPhotoCaptured$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(photoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onError(errorArg: ErrorInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.meta_wearables.WearablesFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
